export const meta = {
  name: 'dcc-extract-incremental',
  description: 'Sequentially extract DCC characters chapter-by-chapter against a running registry',
  phases: [
    { title: 'Extract', detail: 'chapters in reading order, each matched against the known-character index' },
    { title: 'Describe', detail: 'describe newly-introduced entities in parallel' },
  ],
};

// ===== per-book constants (generated by gen-workflow.ts) =====
const bookNumber = 1;
const sectionDir = '';
const sectionFiles = [];
const startIndex = [];           // compact prior registry: {id, canonicalName, aliases, type}
const startBooksProcessed = [];
// ===================================================

// deterministic helpers mirroring src/registry.ts (the sandbox can't import project files)
function normalizeName(name) {
  return name.toLowerCase().replace(/[‘’']/g, '').replace(/[^a-z0-9]+/g, ' ').trim();
}
function makeId(name, existing) {
  const base = normalizeName(name).replace(/\s+/g, '-') || 'entity';
  let id = base;
  let n = 2;
  while (existing.has(id)) id = `${base}-${n++}`;
  return id;
}

// Retry wrapper: agent() returns null on terminal API errors (e.g. Overloaded).
const agentRetry = async (prompt, opts, tries = 4) => {
  for (let attempt = 1; attempt <= tries; attempt++) {
    const label = attempt > 1 ? `${opts.label} (retry ${attempt - 1})` : opts.label;
    const res = await agent(prompt, { ...opts, label });
    if (res) return res;
    if (attempt < tries) log(`${opts.label}: null result, retrying (${attempt}/${tries - 1})`);
  }
  log(`${opts.label}: FAILED after ${tries} attempts`);
  return null;
};

// Matching index (compact); grows as new entities are discovered this book.
const index = startIndex.map((e) => ({ ...e }));
const ids = new Set(index.map((e) => e.id));
const newById = new Map();   // entities introduced this book (full objects)
const matched = [];          // { id, anchor, aliases } for already-known entities
const snippetsById = new Map();
const hintsById = new Map();

const addSnippet = (id, s) => {
  if (!s) return;
  const arr = snippetsById.get(id) || [];
  if (arr.length < 6 && !arr.includes(s)) { arr.push(s); snippetsById.set(id, arr); }
};
const addHint = (id, h) => {
  if (!h) return;
  const arr = hintsById.get(id) || [];
  if (arr.length < 4 && !arr.includes(h)) { arr.push(h); hintsById.set(id, arr); }
};

const extractSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    matched: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string', description: 'id of an already-known entity from the provided index' },
          anchor: { type: 'string' },
          aliases: {
            type: 'array',
            items: { type: 'string' },
            description: 'Any NEW name-forms seen here (esp. Crawler #IDs, titles, full names). [] if none.',
          },
        },
        required: ['id', 'anchor', 'aliases'],
      },
    },
    new: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          name: { type: 'string' },
          aliases: { type: 'array', items: { type: 'string' } },
          type: { type: 'string', enum: ['person', 'creature', 'faction', 'ai_system', 'place', 'other'] },
          tag: { type: 'string', enum: ['in_world', 'real_world_ref', 'media_ref', 'item_object'] },
          roleHint: { type: 'string' },
          mentions: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              properties: { anchor: { type: 'string' }, snippet: { type: 'string' } },
              required: ['anchor', 'snippet'],
            },
          },
        },
        required: ['name', 'aliases', 'type', 'tag', 'roleHint', 'mentions'],
      },
    },
  },
  required: ['matched', 'new'],
};

const describeSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    descriptions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string' },
          description: { type: 'string' },
          significance: { type: 'string', enum: ['major', 'supporting', 'minor', 'mentioned'] },
        },
        required: ['id', 'description', 'significance'],
      },
    },
  },
  required: ['descriptions'],
};

const extractPrompt = (path, idx) =>
  `You are extracting named entities from ONE chapter of "Dungeon Crawler Carl" by Matt Dinniman (Book ${bookNumber}), processed in reading order.

Use the Read tool to read this file: ${path}

Each line is annotated like [B${bookNumber}·C3·¶5]; the token inside the brackets is the EXACT citation for that paragraph.

ALREADY-KNOWN entities discovered in earlier chapters/books (JSON: id, canonicalName, aliases, type):
${JSON.stringify(idx)}

For EVERY paragraph in which a qualifying entity appears:
- If it refers to an already-known entity above — by name, alias, title, epithet, or context (e.g. "the cat" = Princess Donut, "the Queen" = Princess Donut) — add an entry to "matched" with that entity's exact id, the exact anchor, and an "aliases" array of any NEW name-forms for it that appear here (otherwise []).
- Otherwise add it to "new": name (clearest form), aliases used here, type (person|creature|faction|ai_system|place|other), tag, a short factual roleHint, and mentions [{anchor, snippet}].

CRAWLER NUMBERS (high priority):
- Crawler IDs like "Crawler #4,122" are key identifiers. ALWAYS capture the crawler number as an alias for the crawler it belongs to — in the "aliases" of a matched entry if known, or the "aliases" of a new entry if first seen. Tie the number to the correct person when the text makes it clear.
- Likewise capture other distinct name-forms as aliases: full names, titles, epithets, nicknames.

EXHAUSTIVE APPEARANCE LOGGING:
- Log EVERY paragraph (¶) where an entity appears — one matched entry per (entity, paragraph). If Princess Donut appears in 14 paragraphs, emit 14 matched entries. Same for new entities: list every paragraph mention.

WHAT COUNTS AS AN ENTITY:
- Include only NAMED proper nouns or a specifically individuated entity: named people, named creatures/pets, named bosses, named factions/orgs/companies, distinct AI/system voices, named places, named items.
- DO NOT include generic species, monster types, roles, or common-noun categories ("goblin", "mob", "crawlers" as a group, "human", "safe room", "boss"). Only the SPECIFIC named instance counts.
- When unsure whether something is a named individual vs a generic category, EXCLUDE it.

MATCHING NORMALIZATION:
- Treat title/role prefixes as the same entity: "Crawler Frank Q" = "Frank Q". Match case-insensitively and ignore punctuation.

tag meanings:
- in_world: a real entity inside the story world
- real_world_ref: an actual real-world person/company/place referenced (Amazon, Charles Bronson)
- media_ref: a pop-culture / fictional-media reference (Baby Yoda, Call of Duty)
- item_object: a named item, weapon, achievement, in-world show/program, or product

Rules:
- Only use anchors that literally appear in the file; copy them verbatim.
- If an entity is already in the known list, it goes in "matched" (with its id), never in "new".
- One row per entity within "new" (collect ALL its paragraph mentions into that row's mentions array).`;

const describePrompt = (batch) =>
  `You are writing reference descriptions of newly-introduced characters/entities in "Dungeon Crawler Carl" by Matt Dinniman.

For each entity below, write a 2-4 sentence "description" and assign a "significance" (major | supporting | minor | mentioned). Full-series spoilers are allowed; use well-established canon, but ground specific claims in the provided role hints / snippets and do not invent. Return one entry per input id.

Entities (JSON):
${JSON.stringify(batch)}`;

// ---- Phase 1: Extract (sequential, in reading order) ----
phase('Extract');
let dropped = 0;
for (let i = 0; i < sectionFiles.length; i++) {
  const path = `${sectionDir}/${sectionFiles[i]}`;
  const label = sectionFiles[i].replace(/\.txt$/, '');
  const res = await agentRetry(extractPrompt(path, index), {
    schema: extractSchema,
    phase: 'Extract',
    label: `extract:${label}`,
  });
  if (!res) continue;

  for (const m of (res.matched || [])) {
    if (!ids.has(m.id)) { dropped++; continue; }
    matched.push({ id: m.id, anchor: m.anchor, aliases: m.aliases || [] });
  }
  for (const f of (res.new || [])) {
    const id = makeId(f.name, ids);
    ids.add(id);
    const anchors = [...new Set((f.mentions || []).map((x) => x.anchor))];
    const first = (f.mentions || [])[0] || null;
    const ent = {
      id,
      canonicalName: f.name,
      aliases: [...new Set(f.aliases || [])],
      type: f.type,
      tags: [f.tag],
      significance: 'minor',
      description: '',
      firstAppearance: first ? { anchor: first.anchor, snippet: first.snippet } : null,
      appearances: anchors,
    };
    newById.set(id, ent);
    index.push({ id, canonicalName: ent.canonicalName, aliases: ent.aliases, type: ent.type });
    for (const mn of (f.mentions || [])) addSnippet(id, mn.snippet);
    addHint(id, f.roleHint);
  }
  if ((i + 1) % 10 === 0 || i === sectionFiles.length - 1) {
    log(`Processed ${i + 1}/${sectionFiles.length} sections — ${newById.size} new entities, ${matched.length} matched mentions`);
  }
}
if (dropped > 0) log(`Note: dropped ${dropped} matched mentions with unknown ids`);

// ---- Phase 2: Describe (new entities only; parallel batches) ----
phase('Describe');
const toDescribe = [...newById.values()];
const BATCH = 10;
const batches = [];
for (let i = 0; i < toDescribe.length; i += BATCH) {
  batches.push(toDescribe.slice(i, i + BATCH).map((e) => ({
    id: e.id,
    canonicalName: e.canonicalName,
    type: e.type,
    aliases: e.aliases,
    roleHints: hintsById.get(e.id) || [],
    snippets: snippetsById.get(e.id) || [],
  })));
}
const describeResults = await parallel(batches.map((batch, bi) => () =>
  agentRetry(describePrompt(batch), { schema: describeSchema, phase: 'Describe', label: `describe:batch-${bi + 1}` }),
));
const descById = new Map();
for (const r of describeResults) {
  if (!r || !Array.isArray(r.descriptions)) continue;
  for (const d of r.descriptions) descById.set(d.id, d);
}
for (const ent of newById.values()) {
  const d = descById.get(ent.id);
  if (d) { ent.description = d.description; ent.significance = d.significance; }
}

log(`Done: ${newById.size} new entities, ${matched.length} matched mentions for book ${bookNumber}`);
return {
  booksProcessed: [...startBooksProcessed, bookNumber],
  matched,
  newEntities: [...newById.values()],
};
