export const meta = {
  name: 'dcc-redescribe-incremental',
  description: 'Re-describe DCC entities chapter-by-chapter with spoiler-bounded versioned descriptions',
  phases: [
    { title: 'Redescribe', detail: 'chapters in reading order; emit a new version only on material change' },
  ],
};

// ===== per-book constants (generated by gen-redescribe.ts) =====
const bookNumber = 1;
const sectionDir = '';
const chapters = [];   // [{ file, label, entities: [{ id, anchor, canonicalName, type }] }]
const seed = {};       // { id: { description, significance } }
// ===================================================

// Retry wrapper: agent() returns null on terminal API errors (e.g. Overloaded).
const agentRetry = async (prompt, opts, tries = 4) => {
  for (let attempt = 1; attempt <= tries; attempt++) {
    const label = attempt > 1 ? `${opts.label} (retry ${attempt - 1})` : opts.label;
    const res = await agent(prompt, { ...opts, label });
    if (res) return res;
    if (attempt < tries) log(`${opts.label}: null result, retrying (${attempt}/${tries - 1})`);
  }
  log(`${opts.label}: FAILED after ${tries} attempts`);
  return null;
};

const schema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    updates: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string', description: 'id of an entity listed for this chapter' },
          description: { type: 'string', description: '2-4 sentences using ONLY info through this chapter' },
          significance: { type: 'string', enum: ['major', 'supporting', 'minor', 'mentioned'] },
        },
        required: ['id', 'description', 'significance'],
      },
    },
  },
  required: ['updates'],
};

const prompt = (path, entities) =>
  `You are writing SPOILER-BOUNDED reference descriptions for entities in "Dungeon Crawler Carl" by Matt Dinniman, Book ${bookNumber}, processed in strict reading order.

Read this chapter file with the Read tool: ${path}
Each paragraph is annotated like [B${bookNumber}·C3·¶5].

Below are the entities that appear in THIS chapter, each with the description a reader knows SO FAR (from earlier chapters), or null if not yet introduced:
${JSON.stringify(entities)}

For EACH entity, decide whether THIS chapter introduces it or materially changes/develops what a reader knows about it (a new role, relationship, ability, revelation, or status change — not a mere re-appearance).
- If yes: return an entry with a fresh 2-4 sentence "description" written using ONLY information available UP TO AND INCLUDING this chapter. NO later-chapter or later-book knowledge, NO outside canon or spoilers. Set "significance" (major|supporting|minor|mentioned) as warranted by what's known so far.
- If this chapter adds nothing materially new about the entity: OMIT it from "updates".

Ground every claim in this chapter's text or the entity's prior description. Do not invent. Return ONLY the new/changed entities in "updates" (it is correct and expected for "updates" to be shorter than the input list, often empty).`;

phase('Redescribe');
const state = new Map(Object.entries(seed));
const events = [];
for (let i = 0; i < chapters.length; i++) {
  const ch = chapters[i];
  if (!ch.entities.length) continue;
  const withCurrent = ch.entities.map((e) => ({
    id: e.id,
    canonicalName: e.canonicalName,
    type: e.type,
    current: state.get(e.id) ? state.get(e.id).description : null,
  }));
  const res = await agentRetry(prompt(`${sectionDir}/${ch.file}`, withCurrent), {
    schema,
    phase: 'Redescribe',
    label: `redescribe:B${bookNumber}·${ch.label}`,
  });
  if (!res || !Array.isArray(res.updates)) continue;
  const anchorById = new Map(ch.entities.map((e) => [e.id, e.anchor]));
  for (const u of res.updates) {
    const anchor = anchorById.get(u.id);
    if (!anchor) continue; // ignore ids not listed for this chapter
    events.push({ id: u.id, anchor, description: u.description, significance: u.significance });
    state.set(u.id, { description: u.description, significance: u.significance });
  }
  if ((i + 1) % 10 === 0 || i === chapters.length - 1) {
    log(`B${bookNumber}: ${i + 1}/${chapters.length} chapters, ${events.length} versions`);
  }
}

log(`Done: book ${bookNumber}, ${events.length} description versions`);
return { bookNumber, events };
