export const meta = {
  name: 'dcc-redescribe-incremental',
  description: 'Re-describe DCC entities chapter-by-chapter with spoiler-bounded versioned descriptions + aliases',
  phases: [
    { title: 'Redescribe', detail: 'chapters in reading order; emit a new description/alias version only when newly revealed' },
  ],
};

// ===== per-book constants (generated by gen-redescribe.ts) =====
const bookNumber = 1;
const sectionDir = '';
const chapters = [];     // [{ file, label, entities: [{ id, anchor }] }]
const entityMeta = {};   // { id: { canonicalName, type } }
const seed = {};         // { id: { description, significance } }
const aliasesById = {};  // { id: [registry aliases] }
// ===================================================

// Retry wrapper: agent() returns null on terminal API errors (e.g. Overloaded).
const agentRetry = async (prompt, opts, tries = 4) => {
  for (let attempt = 1; attempt <= tries; attempt++) {
    const label = attempt > 1 ? `${opts.label} (retry ${attempt - 1})` : opts.label;
    const res = await agent(prompt, { ...opts, label });
    if (res) return res;
    if (attempt < tries) log(`${opts.label}: null result, retrying (${attempt}/${tries - 1})`);
  }
  log(`${opts.label}: FAILED after ${tries} attempts`);
  return null;
};

const schema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    descriptions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string', description: 'id of an entity listed for this chapter' },
          description: { type: 'string', description: '2-4 sentences using ONLY info through this chapter' },
          significance: { type: 'string', enum: ['major', 'supporting', 'minor', 'mentioned'] },
        },
        required: ['id', 'description', 'significance'],
      },
    },
    aliases: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string', description: 'id of an entity listed for this chapter' },
          seen: {
            type: 'array',
            items: { type: 'string' },
            description: 'candidate aliases whose EXACT form appears in this chapter (subset of the entity\'s candidateAliases)',
          },
        },
        required: ['id', 'seen'],
      },
    },
  },
  required: ['descriptions', 'aliases'],
};

const prompt = (path, entities) =>
  `You are maintaining SPOILER-BOUNDED reference data for entities in "Dungeon Crawler Carl" by Matt Dinniman, Book ${bookNumber}, processed in strict reading order.

Read this chapter file with the Read tool: ${path}
Each paragraph is annotated like [B${bookNumber}·C3·¶5].

Below are the entities that appear in THIS chapter. Each has the description a reader knows SO FAR ("current", or null if not yet introduced) and "candidateAliases" — known name-forms for it that have NOT yet been seen earlier:
${JSON.stringify(entities)}

Two tasks:

1) DESCRIPTIONS ("descriptions"): For each entity, decide whether THIS chapter introduces it or materially changes/develops what a reader knows (a new role, relationship, ability, revelation, or status change — not a mere re-appearance). If yes, return {id, description, significance} with a fresh 2-4 sentence description using ONLY information available UP TO AND INCLUDING this chapter — NO later-chapter/later-book knowledge, NO outside canon. Otherwise omit it. Ground claims in the chapter text or the prior description; do not invent.

2) ALIASES ("aliases"): For each entity, return {id, seen} where "seen" lists the candidateAliases whose EXACT form actually appears in THIS chapter's text (referring to this entity). Omit entities with no candidate appearing here; "seen" may be empty/omitted. The candidateAliases list is for MATCHING ONLY — do NOT let it inform the description (it may contain forms not yet revealed in prose).

Return "descriptions" and "aliases" as arrays (either may be empty).`;

phase('Redescribe');
const state = new Map(Object.entries(seed));
const emitted = new Map(); // id -> Set of aliases already emitted
const descriptionEvents = [];
const aliasEvents = [];

for (let i = 0; i < chapters.length; i++) {
  const ch = chapters[i];
  if (!ch.entities.length) continue;
  const withCurrent = ch.entities.map((e) => ({
    id: e.id,
    canonicalName: (entityMeta[e.id] || {}).canonicalName || e.id,
    type: (entityMeta[e.id] || {}).type || 'other',
    current: state.get(e.id) ? state.get(e.id).description : null,
    candidateAliases: (aliasesById[e.id] || []).filter((a) => !(emitted.get(e.id) && emitted.get(e.id).has(a))),
  }));
  const res = await agentRetry(prompt(`${sectionDir}/${ch.file}`, withCurrent), {
    schema,
    phase: 'Redescribe',
    label: `redescribe:B${bookNumber}·${ch.label}`,
  });
  if (!res) continue;
  const anchorById = new Map(ch.entities.map((e) => [e.id, e.anchor]));

  for (const u of (res.descriptions || [])) {
    const anchor = anchorById.get(u.id);
    if (!anchor) continue; // ignore ids not listed for this chapter
    descriptionEvents.push({ id: u.id, anchor, description: u.description, significance: u.significance });
    state.set(u.id, { description: u.description, significance: u.significance });
  }

  for (const a of (res.aliases || [])) {
    const anchor = anchorById.get(a.id);
    if (!anchor) continue;
    const candidates = new Set(aliasesById[a.id] || []);
    let set = emitted.get(a.id);
    if (!set) { set = new Set(); emitted.set(a.id, set); }
    for (const alias of (a.seen || [])) {
      if (!candidates.has(alias) || set.has(alias)) continue; // only first occurrences of real candidates
      aliasEvents.push({ id: a.id, anchor, alias });
      set.add(alias);
    }
  }

  if ((i + 1) % 10 === 0 || i === chapters.length - 1) {
    log(`B${bookNumber}: ${i + 1}/${chapters.length} chapters, ${descriptionEvents.length} desc + ${aliasEvents.length} alias versions`);
  }
}

log(`Done: book ${bookNumber}, ${descriptionEvents.length} description + ${aliasEvents.length} alias versions`);
return { bookNumber, descriptionEvents, aliasEvents };
