import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { toIndex } from "./registry.js";
import type { BookManifest, Registry } from "./types.js";

const START = "// ===== per-book constants";
const END = "// ===================================================";

/** Build the per-book constants block the workflow script expects between its markers. */
export function buildConstants(
  bookNumber: number,
  sectionDir: string,
  sectionFiles: string[],
  startIndex: unknown[],
  startBooksProcessed: number[],
): string {
  return [
    `${START} (generated by gen-workflow.ts) =====`,
    `const bookNumber = ${bookNumber};`,
    `const sectionDir = ${JSON.stringify(sectionDir)};`,
    `const sectionFiles = ${JSON.stringify(sectionFiles)};`,
    `const startIndex = ${JSON.stringify(startIndex)};`,
    `const startBooksProcessed = ${JSON.stringify(startBooksProcessed)};`,
    END,
  ].join("\n");
}

/** Replace the constants block in the workflow script source with a freshly built one. */
export function injectConstants(scriptSource: string, constants: string): string {
  const start = scriptSource.indexOf(START);
  const endMarker = scriptSource.indexOf(END, start);
  if (start === -1 || endMarker === -1) throw new Error("Could not find constants markers in workflow script");
  const end = endMarker + END.length;
  return scriptSource.slice(0, start) + constants + scriptSource.slice(end);
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const repoRoot = join(here, "..");
  const bookNumber = Number.parseInt(process.argv[2] ?? "", 10);
  if (!Number.isFinite(bookNumber)) {
    console.error("usage: tsx src/gen-workflow.ts <bookNumber>");
    process.exit(1);
  }

  const registry = JSON.parse(readFileSync(join(repoRoot, "output", "registry.json"), "utf8")) as Registry;
  const manifest = JSON.parse(
    readFileSync(join(repoRoot, "data", `book${bookNumber}`, "manifest.json"), "utf8"),
  ) as BookManifest;

  const sectionDir = join(repoRoot, "data", `book${bookNumber}`, "sections");
  const sectionFiles = manifest.sections.map((s) => s.file);
  const reprocessing = registry.booksProcessed.includes(bookNumber);
  const startIndex = reprocessing ? [] : toIndex(registry);
  const startBooksProcessed = registry.booksProcessed.filter((b) => b !== bookNumber);

  const scriptPath = join(repoRoot, "data", "_wf", "book-extract.js");
  const source = readFileSync(scriptPath, "utf8");
  const constants = buildConstants(bookNumber, sectionDir, sectionFiles, startIndex, startBooksProcessed);
  writeFileSync(scriptPath, injectConstants(source, constants), "utf8");

  console.log(
    `gen-workflow: book ${bookNumber} — ${sectionFiles.length} sections, seeded from ${startIndex.length} prior entities (books ${startBooksProcessed.join(", ") || "none"})`,
  );
}

const invokedDirectly = process.argv[1] === fileURLToPath(import.meta.url);
if (invokedDirectly) main();
